# Generated by Django 4.2 on 2025-02-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        # Rename indexes as detected by makemigrations
        migrations.RenameIndex(
            model_name='reviewanswer',
            old_name='performance_answer_employer_period_idx',
            new_name='perf_answ_emp_period_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewanswer',
            old_name='performance_answer_respondent_period_idx',
            new_name='perf_answ_resp_period_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewlog',
            old_name='performance_reviewlog_context_status_idx',
            new_name='perf_revlog_ctx_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reviewlog',
            old_name='performance_reviewlog_token_idx',
            new_name='perf_revlog_token_idx',
        ),
        migrations.RenameIndex(
            model_name='sitenotification',
            old_name='performance_notification_recipient_idx',
            new_name='perf_notif_recipient_idx',
        ),
        migrations.RenameIndex(
            model_name='sitenotification',
            old_name='performance_notification_context_idx',
            new_name='perf_notif_context_idx',
        ),
        migrations.RenameIndex(
            model_name='taskreviewanswer',
            old_name='performance_task_answer_task_resp_idx',
            new_name='perf_task_answ_resp_idx',
        ),
        migrations.RenameIndex(
            model_name='taskreviewanswer',
            old_name='performance_task_answer_task_employer_idx',
            new_name='perf_task_answ_emp_idx',
        ),
        migrations.RenameIndex(
            model_name='teamrelation',
            old_name='performance_team_relation_employer_idx',
            new_name='perf_team_rel_emp_idx',
        ),
    ]