# Generated by ChatGPT
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0003_employer_activation_date_skillquestion_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillReviewFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                ("shared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_feedbacks",
                        to="performance.employer",
                    ),
                ),
                (
                    "log",
                    models.OneToOneField(
                        help_text="Skill review log awaiting manager response",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="performance.reviewlog",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
