# Generated by Django 4.2 on 2025-11-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0005_add_skill_review_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("pending_email", "Pending email"),
                    ("awaiting_feedback", "Awaiting feedback"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
